Repository qaidjoharj53/Banking_System, pull requests merged in 2023-10, with the labels that each got.

#2 Update README.md
  README.md
Labels: documentation, good first issue, Hacktoberfest-accepted

#3 documentations created
  Contributing.md
  code_of_conduct.md
Labels: documentation, good first issue, Hacktoberfest-accepted

#7 Create python-app.yml
  .github/workflows/python-app.yml
Labels: documentation, enhancement, Hacktoberfest-accepted

#8 formated code to increase the readibility
  BankingSystem.py
Labels: enhancement, Hacktoberfest-accepted

#9 added gui in the application
  GUI/__pycache__/account_manager.cpython-311.pyc
  GUI/__pycache__/gui.cpython-311.pyc
  GUI/main.py
Labels: enhancement, Hacktoberfest-accepted

#10 Error handling using Try/Exception blocks
  BankingSystem.py
Labels: enhancement, Hacktoberfest-accepted

#12 Linking code with mysql database
  BankingSystem.py
Labels: enhancement, Hacktoberfest-accepted
